<div class="accordion">
    <div class="accordion-item active"><div class="accordion-header"><h5><?= t('What is Apex Legends Rank Boosting?') ?></h5></div><div class="accordion-content" style="display:block;"><p><?= t('Select your current tier, division, and RP together with the desired target. A high-ranked Apex booster completes Ranked matches until the purchased progression is reached.') ?></p></div></div>
    <div class="accordion-item"><div class="accordion-header"><h5><?= t('How does the exact RP selection work?') ?></h5></div><div class="accordion-content"><p><?= t('For RP-based tiers, enter the current and target RP shown on the account. The form keeps the tier and points synchronized so the price covers the exact progression instead of only whole ranks.') ?></p></div></div>
    <div class="accordion-item"><div class="accordion-header"><h5><?= t('Can I choose Solo or Duo Apex boosting?') ?></h5></div><div class="accordion-content"><p><?= t('Solo means the booster plays on your account. With Duo, you play alongside an experienced booster from your own account. Available modes and their prices are shown before purchase.') ?></p></div></div>
    <div class="accordion-item"><div class="accordion-header"><h5><?= t('Can I request specific Legends?') ?></h5></div><div class="accordion-content"><p><?= t('Legend preferences can be selected when the option is available. Giving the booster several suitable choices helps maintain strong team composition and adapt to the current Ranked meta.') ?></p></div></div>
    <div class="accordion-item"><div class="accordion-header"><h5><?= t('Can I watch the Apex boost live?') ?></h5></div><div class="accordion-content"><p><?= t('Add Stream Games to watch eligible Solo sessions. You can also monitor order progress and communicate with the assigned booster through your dashboard.') ?></p></div></div>
    <div class="accordion-item"><div class="accordion-header"><h5><?= t('What does Priority Boost Completion do?') ?></h5></div><div class="accordion-content"><p><?= t('Priority places the order ahead of standard assignments and can reduce the waiting time before play begins. Queue conditions and the selected RP target still influence completion time.') ?></p></div></div>
    <div class="accordion-item"><div class="accordion-header"><h5><?= t('How is Master rank progression handled?') ?></h5></div><div class="accordion-content"><p><?= t('Master is an open RP ladder rather than a normal division tier. Enter the precise current and desired RP so the calculator can price the requested progression correctly.') ?></p></div></div>
    <div class="accordion-item"><div class="accordion-header"><h5><?= t('Can I use my account while the order is active?') ?></h5></div><div class="accordion-content"><p><?= t('Coordinate personal play time with the booster in the dashboard and never log in during an active Solo session. Duo customers continue playing from their own account as part of the service.') ?></p></div></div>
</div>
