<?= $this->layout('admin/layouts/main', ['meta' => $meta ?? ['title'=>'Top Up Orders']]) ?>
<?php
$orders = is_array($orders ?? null) ? $orders : [];
function lb_ato_h($v){return htmlspecialchars((string)$v, ENT_QUOTES, 'UTF-8');}
function lb_ato_money($c,$cur='EUR'){return (strtoupper((string)$cur)==='USD'?'$':'€').number_format(((int)$c)/100,2);}
function lb_ato_amount($v){$r=trim((string)$v); if($r!=='' && is_numeric($r)) return rtrim(rtrim(number_format((float)$r,2,'.',''),'0'),'.'); return $r;}
function lb_ato_wait($r){$v=(int)($r['waiting_time_value']??0);$u=strtolower((string)($r['waiting_time_unit']??'minutes'));return $u==='hours'?$v.' h':($u==='days'?$v.' d':$v.' min');}
?>
<style>.ato{padding:22px;color:#fff}.atoHead,.atoPanel{background:#25282a;border:1px solid rgba(255,255,255,.08);border-radius:18px}.atoHead{padding:20px 22px;margin-bottom:16px;display:flex;align-items:center;justify-content:space-between}.atoTitle{font-weight:950;font-size:1.35rem}.atoSub{color:#9ca3af}.atoTable{width:100%;border-collapse:collapse}.atoTable th{padding:14px;color:#9ca3af;font-size:.72rem;text-transform:uppercase;background:rgba(255,255,255,.035);text-align:left}.atoTable td{padding:14px;border-top:1px solid rgba(255,255,255,.07);vertical-align:middle}.atoOffer{display:flex;align-items:center;gap:10px}.atoIcon{width:38px;height:38px;border-radius:12px;background:rgba(124,92,255,.16);display:grid;place-items:center;overflow:hidden}.atoIcon img{width:100%;height:100%;object-fit:contain;padding:6px}.atoBtn{display:inline-flex;align-items:center;justify-content:center;border-radius:10px;background:#7c5cff;color:#fff;text-decoration:none;font-weight:900;padding:8px 12px}.atoStatus{border-radius:999px;background:rgba(34,197,94,.14);border:1px solid rgba(34,197,94,.25);color:#86efac;padding:5px 9px;font-weight:900;font-size:.72rem}</style>
<div class="ato"><div class="atoHead"><div><div class="atoTitle">Top Up Orders</div><div class="atoSub"><?= count($orders) ?> orders total</div></div></div><div class="atoPanel"><table class="atoTable"><thead><tr><th>ID</th><th>Top Up</th><th>Seller</th><th>Client</th><th>Region</th><th>Price</th><th>Waiting</th><th>Status</th><th></th></tr></thead><tbody><?php if(!$orders): ?><tr><td colspan="9" style="text-align:center;color:#9ca3af;padding:44px">No top up orders yet.</td></tr><?php endif; ?><?php foreach($orders as $o): $id=(int)($o['id']??0); $game=($o['game_name']??'') ?: ($o['db_game_name']??'Game'); ?><tr><td>#<?= $id ?></td><td><div class="atoOffer"><span class="atoIcon"><?php if(!empty($o['game_icon'])): ?><img src="<?= lb_ato_h($o['game_icon']) ?>" alt=""><?php else: ?><i class="fa-duotone fa-coins"></i><?php endif; ?></span><div><strong><?= lb_ato_h($o['offer_title'] ?? 'Top Up') ?></strong><div class="atoSub"><?= lb_ato_h($game) ?> · <?= lb_ato_h(trim(lb_ato_amount($o['offer_amount']??'').' '.($o['offer_unit']??''))) ?></div></div></div></td><td><?= lb_ato_h($o['seller_username'] ?? 'Seller') ?></td><td><?= lb_ato_h($o['client_username'] ?? $o['client_email'] ?? 'Client') ?></td><td><?= lb_ato_h($o['region'] ?? 'Global') ?></td><td><strong><?= lb_ato_money($o['price'] ?? 0, $o['currency'] ?? 'EUR') ?></strong></td><td><?= lb_ato_h(lb_ato_wait($o)) ?></td><td><span class="atoStatus"><?= lb_ato_h(strtoupper((string)($o['status'] ?? 'PAID'))) ?></span></td><td><a class="atoBtn" href="<?= BASE_URL ?>/admin-area/top-up-order/<?= $id ?>">View</a></td></tr><?php endforeach; ?></tbody></table></div></div>
